# Introdução

A logística empresarial tem se tornado um desafio cada vez maior para as empresas, principalmente depois da ascenção da Indústria 4.0. Assim, um bom planejamento e controle da logística e da cadeia de suprimentos se tornou, além de uma preocupação, uma necessidade e uma estratégia competitiva. O bom dimensionamento de estoques, rotas e transporte podem trazer benefícios significativos no âmbito empresarial.

A Catarina Cerâmicas é uma empresa familiar sediada em Porto Belo/SC bastante representativa no mercado de pisos e azulejos da região sul e sudeste. Com a expansão da marca para regiões mais afastadas, a empresa passou a realizar entregas para os mercados de São Paulo/SP, Palmas/TO e Manaus/AM. Nesse cenário, faz-se necessário o planejamento da gestão da logística e cadeia de suprimentos para a empresa.

O presente trabalho traz o desenvolvimento do projeto logístico para a Catarina Cerâmicas. Ele tem como objetivo retornar um projeto que vise a otimização dos recursos da empresa a fim de reduzir os custos e garantir um serviço de qualidade na entrega dos produtos. O projeto é divido em: (1) Previsão de Demanda; (2) Definição da Localização do Centro de Distribuição; (3) Definição da Roteirização e Modais; (4) Definição de Nível de Serviço e Parâmetros de Estoque; e (5) Custos Logísticos.
