# Revisão da Literatura

Essa seção apresenta uma breve revisão da literatura referente aos métodos aplicados no estudo. Ela dividida em: (1) métodos de previsão de demanda; e (2) método do centro de gravidade.

## Métodos de Previsão de Demanda

Serão  apresetados os métodos abordados para a realização do estudo de previsão de demanda. São considerados três métodos matemáticos diferentes para o modelo preditivo de demanda: (1) Suavização Exponencial, (2) Modelos Autoregressivos Integrados e de Médias Móveis e (3) Redes Neurais Artificiais.

### Suavização Exponencial (SE) {.unlisted .unnumbered}

A Suavização Exponencial (SE) baseia os seus resultados de acordo com os acontecimentos passados, mas, diferentemente de uma média móvel (que considera os eventos passados isobáricos dentro do modelo preditivo), a SE não segue o mesmo efeito. A suavização passa a considerar que os eventos mais recentes e próximos têm maior peso dentro do modelo preditivo quando comparados com eventos mais distantes da série temporal, os quais decaem de forma exponencial da mais recente à mais distante observação (William J, 2011).

O método é um dos mais utilizados dentro da indústria para a predição de produtos e as suas respectivas demandas e a razão para tal é o baixo custo e simplicidade (Teixeira, 2004). Para a utilização deste método, deve-se considerar que o mesmo tem melhores resultados, ou seja, possui melhor ajustamento para séries que não possuem tendência ou sazonalidade. O modelo foi proposto primeiramente por Robert Goodell Brown e a expressão que suporta a suavização exponencial é dada por:


\begin{equation} \label{eq;001}
\widehat{P}_{t+1} = \alpha\widehat{P}_t + (1-\alpha)\widehat{P}_t
\end{equation}

O ponto $\widehat{P}_{t+1}$ é a próxima observação da demanda,  é a constante que varia referente à suavização e seu valor está contido entre 0 e 1 e $\widehat{P}_t$ representa a mais recente observação da série. A Combinação dos valores dos referentes pesos de  com os valores observados atuais $\widehat{P}_t$ geram as previsões para as próximas observações. Note que o valor de $\alpha$ como constante é arbitrário e sua determinação pode ser realizada por diferentes métodos que minimizem os erros causados pela mesma (JONAS *et. al*, 2012).

### Modelos Autoregressivos Integrados e de Médias Móveis (ARIMA) {.unlisted .unnumbered}


Esta metodologia consiste em ajustar modelos autorregressivos integrados de médias móveis, ARIMA(p,d,q), a um conjunto de dados. Para a construção do modelo seguimos um algorítimo no qual a escolha da estrutura do modelo é baseado nos próprios dados. Podemos descrever o algorítimo através dos seguintes passos:

1. Considerar uma classe geral de modelos para a análise;
2. Identificar um modelo com base na análise de autocorrelações, autocorrelações parciais e outros critérios;
3. Estimar os parâmetros do modelo identificado;
Verificar se o modelo ajustado é adequado aos dados através de uma análise de resíduos.
4. Caso o modelo não seja adequado o algoritmo é repetido, voltando à fase de identificação.
5. Existem vários critérios para identificação de um modelo, por isso, é possível identificar modelos diferentes dependendo do critério que foi escolhido para identificação.

#### Modelos Autorregressivos (AR)

Dizemos que o modelo $X_t$, $t$ pertencente a $\mathbb{Z}$ é um modelo autoregressivo de ordem $p$ e escrevemos $X_t \cong AR(p)$ se pudermos escrever da forma:

\begin{equation} \label{eq;002}
X_t = \phi_0 + \phi_1X_t-1 +\dots+ \phi_pX_t-p + \epsilon_t
\end{equation}
Onde  $\phi_0$,  $\phi_1$ e  $\phi_t$ são parâmetros reais, e $\epsilon_t$ são variáveis independentes aleatórias com $E(\epsilon_t) = 0$ e $VAR(\epsilon_t) = \sigma^2$.

#### Modelos de médias móveis (MA).

Consiste em um modelo de médias móveis de ordem p e q, representado por: 

\begin{equation} \label{eq;003}
X_t = \phi_1X_t-1 + \dots + \phi_pX_t-p + \alpha_t - \theta_1\alpha_t-1 -\dots-\theta_q\alpha_t-q 
\end{equation}

Um processo de $MA(p,q)$ tem função de autocovariância infinita, decaindo de acordo com exponenciais ou senóides amortecidas após o lag $p-q$.   

### Redes Neurais Artificiais (RNA)  {.unlisted .unnumbered}

Funcionam analogamente ao cérebro e neurônios, tentando entender padrões e regularidades.Uma de suas vantagens é a aproximação de séries temporais não lineares (Kashei ; Bijari 2010; Zhang 2003).

Modelo descrito por três camadas, entrada, saída e escondida. Os neurônios nestas camadas só se conectam com as camadas subsequentes. A camada escondida necessita ser definida, se for muito grande estará memorizando os padrões assim perdendo capacidade de generalização, se muito pequena necessita de muitas interações, por consequência força computacional para chegar a precisão desejada. (FERNADES, L. G.; PORTUGAL, M. S.; NAVAUX, P. O). Para o sucesso da previsão é necessário dividir as amostras em pares de treinamento e teste e assim avaliar a camada oculta. 

## Método do Centro de Gravidade

O método do centro de gravidade visa encontrar a melhor localização que corresponde ao menor custos de transporte com base em todos os lugares para onde as mercadorias são transportadas. Procura-se, portanto, um local para a instalação do CD intermediário para a entrega nos CD finais. O local da instalação é determinado pelas coordenadas $x$ e $y$ conforme segue na equação \@ref(eq:004). É importante ressaltar que este método não considera fatores qualitativos como incentivos fiscais, restrições sociais, restrições urbanas e facilidade de acesso aos modais de transporte.

\begin{equation} \label{eq:004}
x = \frac{\sum{V_iC_ix_i}}{\sum{V_iC_i}}, \quad y = \frac{\sum{V_iC_iy_i}}{\sum{V_iC_i}}
\end{equation}

Onde:

```{r tabCentroGravidade, echo=FALSE, tab.align='center'}

resultados <- data.frame( T1 = c("$V_i$","$C_i$","$x_i$","$y_i$"),
                          T2 = c("Volume Transportado para o local $i$",
                                 "Custo por unidade de volume transportado para o local $i$",
                                 "Coordenada na direção $x$ do local $i$",
                                 "Coordenada na direção $y$ do local $i$"))
colnames(resultados) <- c("Parâmetro","Descrição")
k <- knitr::kable(resultados, booktabs = T, escape = FALSE, caption = "Parâmetros do Centro de Gravidade")
kableExtra::kable_styling(k, latex_options = "hold_position")
```


Este método também considera outros dois parâmetros:

- **Método P-Centro**: Método que ranqueia as cidades pré-definidas como CDI pela distância máxima entre o CDI até o CDF. Para isto é analisado todas as distâncias do CDI até todos os CDF e com base na distância máxima é ranqueado como melhor opção o CDI que possuir a menor distância máxima;
- **Método P-Mediana**: Utiliza os pontos de demanda definidas, os locais pré-definidos como potenciais para CDI, a distância entre os CDI e CDF e o número p de facilidades a serem instaladas o método que tem como objetivo localizar P CDI para entregar nos centros de demanda com a objetivo de minimizar as distâncias médias ponderadas entre os CDF e os CDI.
