# Metodologia

Nessa seção serão apresentadas as metodologias utilizadas para a realização deste projeto logístico. Ela é dividida em: (1) Previsão de demanda, (2) Definição do Centro de Distribuição e (3) Roteirização.

## Previsão de Demanda {.unlisted .unnumbered}

Para a previsão de demanda foram considerados três modelos principais: (1) Suavização Exponencial, (2) ARIMA e (3) Redes Neurais Artificiais. Cada um dos modelos foi alimentado com os históricos de vendas de cada um dos produtos para cada uma das regiões. A comparação dos modelos foi feita considerando o Erro Percentual Médio Absoluto (MAPE), sendo escolhido como modelo preditivo aquele que tivesse o menor MAPE. Ademais, também foi considerada a análise de resíduos para avaliar o quão precisa é a previsão encontrada.

## Definição do Centro de Distribuição {.unlisted .unnumbered}

Para a realização da escolha do CD foram utilizados um conjunto de dados e métodos para atingirmos um ranking final que nos permitiu priorizar qual o CD mais adequado para a nossa demanda. Foram considerados os critérios: (1) Centro de Gravidade, (2) P-Centro, (3) P-Mediana, (4) Custos e (5) *Lead Time*. Cada um dos critérios recebeu um peso específico, sendo escolhido o Centro de Distribuição que retornasse a melhor nota geral considerando todos os critérios e respectivos pesos estabelecidos

## Roteirização {.unlisted .unnumbered}

Para a definição das melhores rotas e modais, inicialmente foi definido o Dimensionamento de Carga. Para o dimensionamento de carga foram realizadas interações a fim de se otimizar o carregamento, respeitando a área da superfície plana, altura e capacidade de carga dos paletes e modais de transporte.

Com as cargas dimensionadas para cada um dos modais previstos, foi calculado a quantidade de modais necessária para enviar cada um dos produtos. Após estabelecida a quantidade necessária, foi considerado um conjunto de possíveis rotas para avaliação. A avaliação foi feita com base no custo total de cada rota, considerando os diferentes modais disponívels. Como resultado, foi escolhida a rota e o modal que apresentassem o menor custo logístico para a empresa.

## Nível de Serviço e Estoques {.unlisted .unnumbered}

Para a definição de Nível de Serviço foram considerados os *lead times* e a representatividade das demandas em cada um dos mercados consumidores. A definição dos parâmetros de estoque foi feita utilizando as equações \@ref(eq:EST01)-\@ref(eq:EST05), os dados fornececidos pelo problema proposto e um valor de taxa para manter estoque "$i = 0.2$".

## Custo de Estoque {.unlisted .unnumbered}

Para o cálculo de valor de estoque é importante considerar o valor unitário total de cada um dos produtos para os seus respectivos destinos, assim teremos o valor total real de custo do produto. Aliado a este valor temos que adicionar os valores de estoque médio para cada produto e a uma taxa de atrativiadde (TMA). A TMA estabelecida foi de 200% do CDI, contabilizando ao todo 5,3% a.a.

## Custo de Estoque em Trânsito {.unlisted .unnumbered}

Para este custo não foram consideradas perdas durante o trajeto, apenas o custo do capital no tempo do deslocamento. 
Considerado o lead time de entrega até o CD  e o mercado consumidor, para o estado de São Paulo a mercadoria não passa pelo CD em Palmas. Foi adotada a taxa de imobilização de capital  0,015% ao dia e valor de estoque unitário, calculado em valor de estoque.

## Custo de Armazenamento {.unlisted .unnumbered}

O CD de armazenamento sediado na cidade de Palmas possui o segundo menor custo de operação para o armazenamento dentre as 9 opções disponíveis sendo os custos envolvidos no CD divididos em quatro grandes áreas (Armazém, Estoques, Recursos Humanos e Tecnologia da Informação). Os custos fornecidos tem como base a quantidade de pallet disponíveis no CD (350 pallets) onde 100% da demanda média é suprida com 85% da utilização do espaço disponível do CD.

## Faturamento {.unlisted .unnumbered}

O faturamento é calculado pelo valor do “preço caixa” dos produtos MO0021, MO0091 e M01401 multiplicado pela previsão mensal de cada produto. Com isto se obtêm um valor médio dos valores de faturamento dos produtos e da empresa durante os 10 meses. 

